version: '3'

services:
  db:
    build: ./docker/postgis
    image: postgis:9.6
    volumes:
      - .db:/var/lib/postgresql/data
  queue:
    image: rabbitmq
  web:
    build: .
    image: onadata:master
    volumes:
      - .:/srv/onadata
    ports:
      - "3030:3030"
      - "8000:8000"
    depends_on:
      - db
      - queue

